In [21]:
import numpy as np
import pandas as pd

In [22]:
food_df = pd.read_csv('./datasets/preprocessed_food.csv')
recommended_df = pd.read_csv('./datasets/preprocessed_recommendedfordisease.csv')

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor, VotingRegressor, StackingRegressor
from sklearn.svm import SVR


In [24]:
nutritional_cols = ['Energy (kcal)', 'Protein (mg)', 'Carbohydrate (mg)', 'Sugars, total(mg)',
                    'Fiber, total dietary (mg)', 'Total Fat (mg)', 'Fatty acids, total saturated (mg)',
                    'Cholesterol (mg)', 'Niacin (mg)', 'Folic acid ((mg))', 'Choline, total (mg)',
                    'Vitamin C (mg)', 'Vitamin E (alpha-tocopherol) (mg)', 'Calcium (mg)',
                    'Phosphorus (mg)', 'Magnesium (mg)', 'Potassium (mg)', 'Sodium (mg)',
                    'Caffeine (mg)', 'Theobromine (mg)', 'Alcohol (mg)', 'Water(mg)']


In [25]:
disease_limits = recommended_df[nutritional_cols].values

len(disease_limits)

20

In [26]:
# Extract nutrient columns
nutrient_columns = food_df.columns[2:]
food_nutrition = food_df[nutrient_columns].values

len(nutrient_columns),len(food_nutrition)

(22, 6529)

In [27]:
scaler = StandardScaler()
food_nutrition_scaled = scaler.fit_transform(food_nutrition)
disease_limits_scaled = scaler.transform(disease_limits)

len(food_nutrition_scaled),len(disease_limits_scaled)

(6529, 20)

In [28]:
food_nutrition_scaled[0], disease_limits_scaled[0]

(array([-0.96783211, -0.95752708, -0.65907926, -0.03641579, -0.66823404,
        -0.45019565, -0.22359415, -0.28418779, -0.63554542, -0.23183929,
        -0.44898583,  0.00181913, -0.31946786, -0.37141547, -0.98116147,
        -0.65997442, -0.81743153, -0.9859367 , -0.03487977, -0.13055734,
        -0.10191342,  1.10211694]),
 array([-0.9450288 , -0.6592671 , -0.45522729, -0.01081857,  0.03955752,
        -0.66030674, -0.55804227, -0.34230679, -0.43200947, -0.22613381,
        -0.40496891,  0.44405975, -0.09793344, -0.36076346, -0.66873448,
        -0.16728502,  0.05812239, -0.70030712, -0.03487977, -0.13055734,
        -0.10191342,  0.90247398]))

In [32]:
import numpy as np
import pandas as pd
food_df = pd.read_csv('./datasets/preprocessed_food.csv')
recommended_df = pd.read_csv('./datasets/preprocessed_recommendedfordisease.csv')
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor, VotingRegressor, StackingRegressor
from sklearn.svm import SVR

nutritional_cols = ['Energy (kcal)', 'Protein (mg)', 'Carbohydrate (mg)', 'Sugars, total(mg)',
                    'Fiber, total dietary (mg)', 'Total Fat (mg)', 'Fatty acids, total saturated (mg)',
                    'Cholesterol (mg)', 'Niacin (mg)', 'Folic acid ((mg))', 'Choline, total (mg)',
                    'Vitamin C (mg)', 'Vitamin E (alpha-tocopherol) (mg)', 'Calcium (mg)',
                    'Phosphorus (mg)', 'Magnesium (mg)', 'Potassium (mg)', 'Sodium (mg)',
                    'Caffeine (mg)', 'Theobromine (mg)', 'Alcohol (mg)', 'Water(mg)']
disease_limits = recommended_df[nutritional_cols].values

len(disease_limits)
# Extract nutrient columns
nutrient_columns = food_df.columns[2:]
food_nutrition = food_df[nutrient_columns].values
scaler = StandardScaler()
food_nutrition_scaled = scaler.fit_transform(food_nutrition)
disease_limits_scaled = scaler.transform(disease_limits)
food_nutrition_scaled[0], disease_limits_scaled[0]
distance = food_nutrition_scaled - disease_limits_scaled[0]
distance_magnitude = np.linalg.norm(distance, axis=1)

from sklearn.model_selection import train_test_split

X = food_nutrition_scaled
y = distance_magnitude

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Create a LinearRegression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model performance
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('Mean Absolute Error:', mae)

R2 Score: 0.8857496437804155
Mean Absolute Error: 0.7017414604041878


In [9]:
# distances_list = []

# for dist in range(iteration):
#     distance = food_nutrition_scaled - disease_limits_scaled[dist]
#     distances_list.append(distance)

# distances_list[]

In [10]:
# # Convert the list of distances to a NumPy array
# distances_array = np.stack(distances_list)

# # distances_array now contains all the calculated distances
# print("Shape of distances array:", distances_array.shape)

In [53]:
# Calculate distances
distance = food_nutrition_scaled - disease_limits_scaled[3]
distance_magnitude = np.linalg.norm(distance, axis=1)

In [54]:
distance[0], len(distance), len(distance_magnitude)

(array([-3.06827183e-02, -3.43846537e-01, -1.39587951e-01,  1.22158413e-01,
        -6.17280116e-01,  1.72157242e-01,  3.09482125e-01, -1.60316621e-02,
        -1.97509668e-01, -1.84889082e-02, -7.31585283e-02, -4.12811313e-01,
        -2.21925489e-01, -1.14152704e-01, -3.64495080e-01, -4.28863894e-01,
        -6.58111425e-01, -3.65074680e-01, -4.87880151e-04, -1.74566604e-02,
         0.00000000e+00,  1.78840819e-01]),
 6529,
 6529)

In [55]:
from sklearn.model_selection import train_test_split

X = food_nutrition_scaled
y = distance_magnitude

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
X_train, y_train

(array([[ 0.64629198,  1.06364141, -0.12927361, ..., -0.13055734,
         -0.10191342, -0.48959935],
        [ 1.09426475, -1.08078366,  3.39734406, ..., -0.13055734,
         -0.10191342, -2.08131563],
        [ 1.27203172, -0.68349062,  3.12137539, ..., -0.13055734,
         -0.10191342, -2.08506526],
        ...,
        [-0.97494278, -0.75529057, -0.68663096, ..., -0.13055734,
         -0.10191342,  1.04099803],
        [ 0.14854447, -0.51117075, -0.71463433, ..., -0.13055734,
         -0.10191342,  0.35706623],
        [ 0.46141433,  1.21920796, -0.19115202, ..., -0.13055734,
         -0.10191342, -0.42998029]]),
 array([ 4.06464712,  7.27081373, 10.88747061, ...,  1.10818852,
         2.40780682,  4.51480129]))

In [57]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((5223, 22), (5223,), (1306, 22), (1306,))

In [47]:
food_array = np.arange(food_df.shape[1])
print('Array index of food_df\n',food_array)

# Remove 0 and 1 from the array
food_final = np.delete(food_array, [0, 1])
print('Array index of food_df after exluding 0 and 1\n',food_final)

Array index of food_df
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Array index of food_df after exluding 0 and 1
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [48]:
len(food_final)

22

In [18]:
transformers = [
    ('col_tnf', OneHotEncoder(
        sparse_output=False, drop='first'), food_final),
]

## Linear Regression

Note:
MAE is useful when the goal is to minimize the overall error in the model while avoiding large errors. 4. R-squared (R2): This metric measures the proportion of variance in the target variable explained by the model. It ranges from 0 to 1, with higher values indicating better performance.

In [49]:
# Create a LinearRegression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model performance
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('Mean Absolute Error:', mae)

R2 Score: 0.877691874070194
Mean Absolute Error: 0.7222090220162213


## Ridge Regression

In [50]:
# Create a Ridge regression model
model = Ridge(alpha=10)

model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model performance
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('Mean Absolute Error:', mae)

R2 Score: 0.8745891629268543
Mean Absolute Error: 0.7233356382028061


In [51]:
# Create a KNN regression model
model = KNeighborsRegressor(n_neighbors=3)

model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model performance
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('Mean Absolute Error:', mae)

R2 Score: 0.9059786700969351
Mean Absolute Error: 0.260564358570005


In [52]:
model = RandomForestRegressor(n_estimators=100,
                              random_state=3,
                              max_samples=0.5,
                              max_features=0.75,
                              max_depth=15)

model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model performance
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print('R2 Score:', r2)
print('Mean Absolute Error:', mae)

R2 Score: 0.8354281439057737
Mean Absolute Error: 0.314643078546993
